# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arc', '0002_auto_20161208_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uuid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
