# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arc', '0003_auto_20161209_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bimg',
            field=models.CharField(max_length=64),
        ),
    ]
