# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Arc', '0005_auto_20161209_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='id',
        ),
        migrations.AlterField(
            model_name='trade',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trade_goods', serialize=False, to='Arc.book'),
        ),
    ]
